### ISSUE TITLE
Nexus 4 : light sensor always returning 1.0 or 0.0

### ISSUE THREAD

**Issue by vinilox** [ray0711/homeDash#3]
/homedash/sensor/brightness {"sensor":"LGE Light Sensor","unit":"lx","value":"0.0"}
/homedash/sensor/brightness {"sensor":"LGE Light Sensor","unit":"lx","value":"1.0"}

It's consistent with the ambient light but not really precise. :p

**Comment by vinilox** [comment]
It's on the last official ROM and the auto brightness is working.

**Comment by ray0711** [comment]
We just use the default ambient light sensor that android returns. Might be your system has more than one and we get the wrong one :(
There are various apps to list all available sensors and their values on the play store. Can you crosscheck if they report better values and if yes what the sensor names are?

Doesn't mean I know how to solve it yet but worth a try :D

**Comment by vinilox** [comment]
Nevermind, it's just too dark. When I put it close to a bright light it's ok and reporting the same value that the sensor app (only one sensor lux in the nexus 4).
Thanks anyway ! ^^'
